# Generated by Django 5.1 on 2025-03-02 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
    ]
