# Generated by Django 5.1 on 2025-03-02 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_auto_20250303_0229'),
    ]

    operations = [
    ]
