# Generated by Django 5.1 on 2025-03-02 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_auto_20250303_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, default='MISSING_ID', max_length=100, null=True),
        ),
    ]
