# Generated by Django 5.1 on 2025-03-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_alter_booking_razorpay_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='razorpay_order_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
