# Generated by Django 5.1 on 2025-03-03 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_booking_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_title', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('PPD', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fuel', models.CharField(max_length=50)),
                ('model_year', models.IntegerField()),
                ('setting', models.IntegerField()),
                ('img1', models.ImageField(upload_to='car_images/')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('Add', models.TextField()),
                ('postVcl', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='car.postvcl')),
                ('veriform', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='car.veriform')),
            ],
        ),
    ]
