# Generated by Django 5.1 on 2025-03-03 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_cardetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardetails',
            name='Add',
        ),
        migrations.RemoveField(
            model_name='cardetails',
            name='PPD',
        ),
        migrations.RemoveField(
            model_name='cardetails',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='cardetails',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cardetails',
            name='fuel',
        ),
        migrations.RemoveField(
            model_name='cardetails',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='cardetails',
            name='model_year',
        ),
        migrations.RemoveField(
            model_name='cardetails',
            name='name',
        ),
        migrations.RemoveField(
            model_name='cardetails',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='cardetails',
            name='setting',
        ),
        migrations.RemoveField(
            model_name='cardetails',
            name='vehicle_title',
        ),
    ]
