# Generated by Django 5.1 on 2025-03-03 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_remove_cardetails_add_remove_cardetails_ppd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start',
            field=models.DateTimeField(),
        ),
        migrations.DeleteModel(
            name='CarDetails',
        ),
    ]
