# Generated by Django 5.1 on 2025-03-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0009_alter_booking_end_alter_booking_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
